20
happy-of-development/project-hive-api pull request #23
Opened 2023-05-03 01:52 UTC by mogi879

2023-05-03 03:39 UTC, bjbaek requested changes

2023-05-03 03:39 UTC, bjbaek commented on src/main/java/com/hod/project/hive/mapper/TeamMapper.java
> +}
14 라인에 개행 있는데 아래 다른 것도 묶어서 하실거면 개행 추가하시는 게 좋을 듯 합니다.

2023-05-03 03:39 UTC, bjbaek commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +            return;
중괄호 추가 부탁드립니다.
java 코딩 컨벤션에 맞지 않네요.

2023-05-03 03:39 UTC, bjbaek commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +        teamUser = teamMapper.findTeam(id);
teamUser 선언 및 할당이 분리되어 있을 필요는 없어 보입니다. 합쳐 주세요.

2023-05-03 03:39 UTC, bjbaek commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +        }
teamUser null 체크는 위에서 하는 것이 좋아 보입니다.

2023-05-03 09:47 UTC, EungJuLee77 commented on src/main/java/com/hod/project/hive/controller/TeamController.java
> +    TeamService teamService;
모든 클래스 멤버에 private 붙여주세요.

2023-05-03 22:49 UTC, mogi879 commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +            return;
수정 완료

2023-05-03 22:49 UTC, mogi879 commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +        teamUser = teamMapper.findTeam(id);
getTeam 부분 리팩토링 했습니다.

2023-05-03 22:54 UTC, mogi879 commented on src/main/java/com/hod/project/hive/controller/TeamController.java
> +    TeamService teamService;
수정 하였습니다.

2023-05-04 07:04 UTC, bjbaek requested changes

2023-05-04 07:04 UTC, bjbaek commented on src/main/resources/mapper/TeamMapper.xml
> +    </insert>
객체에서 받은 시간으로 insert 되도록 해주세요.
NOW() 함수로 여러번 실행되어 같은 시간이 찍히지 않습니다.

시간이 되시면 밖에서 for 문으로 여러번 insert 하는 것으로 처리하는데
List 로 받아 처리하는 것도 추가해 보시면 좋을 것 같습니다.

2023-05-04 09:03 UTC, mogi879 commented on src/main/resources/mapper/TeamMapper.xml
> +    </insert>
고민해 보겠습니다.

2023-05-04 09:04 UTC, mogi879 commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +    }
리스트로 반환하려고 만든 것인데 리스트로 반환 받을 수 있나요?

2023-05-04 09:04 UTC, mogi879 commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +    }
적용했습니다.

2023-05-04 09:04 UTC, mogi879 commented on src/main/java/com/hod/project/hive/controller/TeamController.java
> +        System.out.println("addTeam : " + request.getId());
적용했습니다.

2023-05-04 09:04 UTC, mogi879 commented on src/main/java/com/hod/project/hive/entity/Team.java
적용했습니다.

2023-05-04 09:04 UTC, mogi879 commented on http/Team.http
병합할때 추가할께요.

2023-05-04 13:39 UTC, bjbaek commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +    }
team 변수가 실제 사용되기 전에  선언하시는게 좋다는 이야기 입니다.

2023-05-08 03:57 UTC, bjbaek requested changes
댓글 확인 후 수정 부탁드립니다.

2023-05-08 03:57 UTC, bjbaek commented on src/main/resources/mapper/TeamMapper.xml
> +    </insert>
List 는 고민해 보시더라도 객체로 부터 받은 시간으로 설정될 수 있도록 수정 부탁드립니다.

2023-05-08 03:57 UTC, bjbaek commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +    }
코드가 글쓰기라면 개행 문자 잘 활용해 주셨으면 합니다.

2023-05-08 04:04 UTC, EungJuLee77 approved these changes

2023-05-08 06:24 UTC, mogi879 commented on src/main/resources/mapper/TeamMapper.xml
> +    </insert>
수정 적용했습니다.

2023-05-08 06:34 UTC, bjbaek requested changes
댓글 확인 부탁드립니다.

2023-05-08 06:34 UTC, bjbaek commented on src/main/java/com/hod/project/hive/service/TeamService.java
> +        request.setCreatedId("1111111"); // 로그인 후 수정 예정
아래와 같이 사용하시면 IDE 에 도움을 받을 수 있습니다.
```java
// TODO: 로그인 후 수정 예정
```

2023-05-08 06:34 UTC, bjbaek commented on src/main/resources/mapper/TeamMapper.xml
> +    <insert id="addTeamUser" parameterType="com.hod.project.hive.dto.TeamUserRequest">
List 변경에 따라 메소드명 변경이 필요할 것 같습니다.
addTeamUser -> addTeamUserList

2023-05-08 06:34 UTC, bjbaek commented on src/main/resources/mapper/TeamMapper.xml
> +        </foreach>
created_date 는 `not null` 이라 null 체크 넣어 주시면 좋을 것 같네요.
음.. 저라면 if 문 null 확인 후 없으면 NOW() 함수를 추가할 듯 싶습니다.

2023-05-08 07:49 UTC, bjbaek requested changes
마직막 일 듯 합니다.

2023-05-08 07:49 UTC, bjbaek commented on src/main/resources/mapper/TeamMapper.xml
> +        </foreach>
, 콤마 뒤에 띄어쓰기 부탁드립니다.
`IFNULL(#{team.createdDate},NOW()),` --> `IFNULL(#{team.createdDate}, NOW()),`

2023-05-08 07:56 UTC, merged